<?php
###########################################
# Config file for imgconcept
# generated by imgconcept_install script
###########################################

# Is imgconcept installed? 
define('installed', true);

# SQL Settings
define('dbhost', 'localhost');
define('dbuser', 'root');
define('dbpass', '');
define('dbname', 'imgconcept');

# Site Settings
define('site_logo', 'img/logo.png');
define('site_name', 'imgconcept');
define('default_skin', 'default');

# Registration Settings
define('captcha', false);
define('anychar', false);
define('avatars', false);
define('avatars_dir', '');

# Rankings
define('rank_5imgs', '');
define('rank_10imgs', '');
define('rank_20imgs', '');
define('rank_50imgs', '');
define('rank_100imgs', '');
# Special Ranks
define('rank_donator', '');
define('rank_admin', '');
define('rank_founder', '');
define('rank_banned', '');
?>